// Mock data for when Convex backend isn't connected
// This allows the app to function and display properly

export const MOCK_PRODUCTS = [
  {
    _id: "prod_001",
    name: "Wireless Bluetooth Headphones",
    description: "Premium noise-cancelling headphones with 30hr battery",
    price: 1299,
    originalPrice: 2999,
    category: "Electronics",
    image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=400",
    inStock: true,
    rating: 4.5,
    reviewCount: 1234,
  },
  {
    _id: "prod_002",
    name: "Cotton Casual T-Shirt",
    description: "100% cotton comfortable everyday wear",
    price: 399,
    originalPrice: 799,
    category: "Fashion",
    image: "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=400",
    inStock: true,
    rating: 4.2,
    reviewCount: 856,
    sizes: ["S", "M", "L", "XL"],
  },
  {
    _id: "prod_003",
    name: "Smart Watch Pro",
    description: "Fitness tracking, heart rate monitor, GPS",
    price: 2499,
    originalPrice: 4999,
    category: "Electronics",
    image: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=400",
    inStock: true,
    rating: 4.7,
    reviewCount: 2341,
  },
  {
    _id: "prod_004",
    name: "Running Shoes",
    description: "Lightweight athletic shoes with cushioning",
    price: 1599,
    originalPrice: 2999,
    category: "Footwear",
    image: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400",
    inStock: true,
    rating: 4.4,
    reviewCount: 1567,
    sizes: ["7", "8", "9", "10"],
  },
  {
    _id: "prod_005",
    name: "Laptop Backpack",
    description: "Waterproof backpack with USB charging port",
    price: 899,
    originalPrice: 1999,
    category: "Accessories",
    image: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=400",
    inStock: true,
    rating: 4.3,
    reviewCount: 923,
  },
  {
    _id: "prod_006",
    name: "Sunglasses UV400",
    description: "Polarized sunglasses with UV protection",
    price: 499,
    originalPrice: 999,
    category: "Accessories",
    image: "https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=400",
    inStock: true,
    rating: 4.1,
    reviewCount: 678,
  },
];

export const MOCK_CART = {
  items: [
    {
      id: "cart_001",
      product_id: "prod_001",
      name: "Wireless Bluetooth Headphones",
      image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=400",
      size: undefined,
      quantity: 1,
      price: 1299,
      original_price: 2999,
      in_stock: true,
    },
    {
      id: "cart_002",
      product_id: "prod_002",
      name: "Cotton Casual T-Shirt",
      image: "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=400",
      size: "M",
      quantity: 2,
      price: 399,
      original_price: 799,
      in_stock: true,
    },
  ],
  price_break_up: [
    { type: "PRODUCT_PRICE", value: 2097 },
    { type: "DISCOUNT", value: -1902 },
    { type: "DELIVERY_CHARGE", value: 0 },
  ],
  total_quantity: 3,
  product_price: 2097,
  original_price: 4597,
  supplier_discount: 2500,
  first_order_discount: 120,
  total_discount: 2620,
  delivery_charge: 0,
  total: 1477,
  effective_total: 1477,
  is_first_order: true,
};

export const MOCK_ADDRESSES = [
  {
    id: "addr_001",
    name: "Rahul Kumar",
    mobile: "9876543210",
    pin: "110001",
    city: "New Delhi",
    state: "Delhi",
    house_number: "123, MG Road",
    area: "Connaught Place",
    landmark: "Near Metro Station",
    address_type: "home",
    is_default: true,
  },
  {
    id: "addr_002",
    name: "Rahul Kumar",
    mobile: "9876543210",
    pin: "400001",
    city: "Mumbai",
    state: "Maharashtra",
    house_number: "456, Linking Road",
    area: "Bandra West",
    landmark: "Opposite Mall",
    address_type: "work",
    is_default: false,
  },
];

export const MOCK_PAYMENT_OPTIONS = [
  {
    type: "cod",
    display_name: "Cash On Delivery",
    description: "Pay when your order arrives",
    enabled: true,
    icon: "cod",
    min_amount: 0,
    max_amount: 5000,
  },
  {
    type: "upi",
    display_name: "UPI",
    description: "Pay via any UPI app",
    enabled: true,
    icon: "upi",
    min_amount: 1,
    max_amount: 100000,
    sub_options: [
      { type: "upi_intent", display_name: "UPI App", description: "Open your UPI app" },
      { type: "upi_qr", display_name: "UPI QR", description: "Scan QR code" },
    ],
  },
  {
    type: "card",
    display_name: "Credit / Debit Card",
    description: "Visa, Mastercard, RuPay",
    enabled: true,
    icon: "card",
    min_amount: 1,
    max_amount: 500000,
  },
];

export const MOCK_USER_PROFILE = {
  userId: "user_001",
  name: "Rahul Kumar",
  email: "rahul@example.com",
  phone: "9876543210",
  is_anonymous: false,
  feature_toggles: {
    price_unbundling: true,
    lottie_animations: true,
    cod_enabled: true,
    upi_enabled: true,
  },
};
